[workspace]
members = ["token"]

[package]
name = "parsr"
description = "a libary for simple parsing"
license = "MIT OR Apache-2.0"
version = "1.0.2"
edition = "2024"

[dependencies]
token-precedence = { path = "token" }
gxhash = "3.5.0"
