[workspace]
members = ["token"]

[package]
name = "parsr"
description = "a libary for simple parsing"
license = "MIT OR Apache-2.0"
version = "1.0.0"
edition = "2024"

[dependencies]
rust-ext = { path = "../rust-ext", features = ["constants"] }
gxhash = "3.5.0"