[workspace]
members = ["token"]

[package]
name = "parsr"
description = "a libary for simple parsing"
license = "MIT OR Apache-2.0"
version = "1.0.3"
edition = "2024"

[dependencies]
token-precedence = { path = "token", version = "1.0.0" }
gxhash = "3.5.0"
